### ISSUE TITLE
sound file not decoding correctly after Pi restart

### ISSUE THREAD

**Issue by JanOosthuizen** [lutzer/node-red-contrib-play-soundfile#2]
Before I restarting Raspberi Pi4 , the sound was working 100%. After restart the sound is very "distorted". It is as if it is not decoded correctly. I thing mpg321 player is used to play the *.wav file instead of aplay.  (See termenal log.jpg)

**Interesting**
1) In can still play the "Dingdong. wav" file with aplayer (sudo aplay /home/pi/Music/Dingdong.wav) and it is very clear sound

**Question**
1) Does contrib-play-soundfile select the appropriate sound player automatically? (I know I have two players installed.  aplay & mpg321 , .... ).  Maybe the software selects the wrong player for the file format.
2) Can I dictate what player should be used. (e.g aplay) for wav files?

Any suggestion is welcome

Regards
Jan

![Termenal](https://user-images.githubusercontent.com/13832199/201491837-228d5000-2cb0-46c3-a27a-1f9239382b62.jpg)
![node Soundfile](https://user-images.githubusercontent.com/13832199/201491838-fe46708f-c362-49ad-8c1c-238194aba698.jpg)
![termenal log](https://user-images.githubusercontent.com/13832199/201491839-972a4dea-e853-4c6f-b814-e33b144254a2.jpg)

**Comment by JanOosthuizen** [comment]
I solved the problem. I un-installed mpg321 (sudo apt-get purge --remove mpg321). By default the player to be used by Pi is "aplay". The Wav files are working 100% know.

**Comment by lutzer** [comment]
oh great that it works now.. i didnt found time to look into your issue yet. the node relies on this npm package: https://github.com/shime/play-sound. you can also choose a different player in the options if the default one does not work properly (for example: `{"player": "aplay"}`

**Comment by JanOosthuizen** [comment]
Hi Luzer. 
I am changing from Raspberi Pi to a Dell PC with Debian 12.
The  "node-red-contrib-play-soundfile" does not work after my PC change. Not sure if the audio software been used is compatible with this block?

Your comment on 29Nov22 you said I can add _**{"player": "aplay"}**_ in the option field.
Is this correct?

Any suggestion is welcome
![Option](https://github.com/lutzer/node-red-contrib-play-soundfile/assets/13832199/c9ff9cf5-fb2b-4d81-88bd-36befe9e9851)

**Comment by JanOosthuizen** [comment]
Debian 12, GNOME Desktop use pipewire (libpipewire 0.3.65) for sound server
